import { University, CareerPath } from "./types";

export const UNIVERSITIES: University[] = [
  {
    name: "Massachusetts Institute of Technology (MIT)",
    country: "USA",
    location: "usa_east",
    bestCourse: "Computer Science & AI",
    tuition: 55000,
    ranking: 1,
    roi: 95,
    scholarshipRate: 60,
    majorStrength: { "computer science": 99, "ai": 99, engineering: 98, business: 85 },
    details: {
      programStrengths: ["Artificial Intelligence", "Aerospace Engineering", "Quantum Computing"],
      campusLife: "Intense academic environment balanced by a vibrant 'hacking' culture and over 500 student organizations.",
      admissionStats: { acceptanceRate: "4.1%", avgSAT: "1520-1580", avgGPA: "4.17" },
    },
  },
  {
    name: "Stanford University",
    country: "USA",
    location: "usa_west",
    bestCourse: "Computer Science & AI",
    tuition: 56000,
    ranking: 2,
    roi: 94,
    scholarshipRate: 55,
    majorStrength: { "computer science": 98, "ai": 98, business: 92, medicine: 88 },
    details: {
      programStrengths: ["Entrepreneurship", "Human-Centered AI", "Biomedical Research"],
      campusLife: "Located in the heart of Silicon Valley with a strong focus on innovation and interdisciplinary collaboration.",
      admissionStats: { acceptanceRate: "3.9%", avgSAT: "1470-1570", avgGPA: "3.96" },
    },
  },
  {
    name: "Harvard University",
    country: "USA",
    location: "usa_east",
    bestCourse: "Medicine",
    tuition: 54000,
    ranking: 3,
    roi: 92,
    scholarshipRate: 58,
    majorStrength: { law: 99, business: 96, medicine: 98, "ai": 85 },
    details: {
      programStrengths: ["Global Governance", "Life Sciences", "Economics"],
      campusLife: "Historic campus with a unique house system that fosters close-knit communities within a large university.",
      admissionStats: { acceptanceRate: "3.4%", avgSAT: "1480-1580", avgGPA: "4.18" },
    },
  },
  {
    name: "University of California, Berkeley",
    country: "USA",
    location: "usa_west",
    bestCourse: "Engineering",
    tuition: 44000,
    ranking: 4,
    roi: 90,
    scholarshipRate: 65,
    majorStrength: { "computer science": 94, "ai": 95, engineering: 93, "environmental science": 90 },
    details: {
      programStrengths: ["Data Science", "Chemical Engineering", "Public Policy"],
      campusLife: "A hub for social activism and diverse perspectives, offering a classic public university experience.",
      admissionStats: { acceptanceRate: "11.4%", avgSAT: "1310-1530", avgGPA: "3.89" },
    },
  },
  {
    name: "University of Oxford",
    country: "UK",
    location: "europe",
    bestCourse: "Medicine",
    tuition: 38000,
    ranking: 5,
    roi: 88,
    scholarshipRate: 70,
    majorStrength: { humanities: 95, "social sciences": 94, medicine: 95, engineering: 85 },
    details: {
      programStrengths: ["Philosophy, Politics and Economics (PPE)", "Clinical Medicine", "Archaeology"],
      campusLife: "Distinctive collegiate system with formal dinners, ancient traditions, and world-class libraries.",
      admissionStats: { acceptanceRate: "14.3%", avgGPA: "3.9+" },
    },
  },
  {
    name: "University of Cambridge",
    country: "UK",
    location: "europe",
    bestCourse: "Engineering",
    tuition: 37000,
    ranking: 6,
    roi: 87,
    scholarshipRate: 68,
    majorStrength: { mathematics: 96, physics: 95, engineering: 92, medicine: 90 },
    details: {
      programStrengths: ["Natural Sciences", "Mathematics", "Computer Science"],
      campusLife: "Strong emphasis on small-group supervision and a rich history of scientific breakthroughs.",
      admissionStats: { acceptanceRate: "15.7%", avgGPA: "3.9+" },
    },
  },
  {
    name: "ETH Zurich",
    country: "Switzerland",
    location: "europe",
    bestCourse: "Engineering",
    tuition: 15000,
    ranking: 7,
    roi: 91,
    scholarshipRate: 75,
    majorStrength: { engineering: 96, "computer science": 92, "ai": 90, "natural sciences": 90 },
    details: {
      programStrengths: ["Robotics", "Architecture", "Cybersecurity"],
      campusLife: "Modern facilities in a global financial hub, known for rigorous technical training.",
      admissionStats: { acceptanceRate: "27%", avgGPA: "3.8+" },
    },
  },
  {
    name: "National University of Singapore",
    country: "Singapore",
    location: "asia",
    bestCourse: "Engineering",
    tuition: 22000,
    ranking: 8,
    roi: 86,
    scholarshipRate: 72,
    majorStrength: { engineering: 90, business: 87, "computer science": 89, "ai": 85 },
    details: {
      programStrengths: ["Supply Chain Management", "Digital Innovation", "Urban Planning"],
      campusLife: "Dynamic multicultural environment with strong links to Asian industry and technology.",
      admissionStats: { acceptanceRate: "5-10%", avgGPA: "3.8+" },
    },
  },
  {
    name: "University of Toronto",
    country: "Canada",
    location: "canada",
    bestCourse: "Medicine",
    tuition: 35000,
    ranking: 9,
    roi: 84,
    scholarshipRate: 65,
    majorStrength: { medicine: 92, "computer science": 86, engineering: 85, "ai": 88 },
    details: {
      programStrengths: ["Machine Learning", "Public Health", "Psychology"],
      campusLife: "Urban campus integrated into one of the world's most diverse cities, offering endless opportunities.",
      admissionStats: { acceptanceRate: "43%", avgGPA: "3.7" },
    },
  },
  {
    name: "University of Michigan",
    country: "USA",
    location: "usa_midwest",
    bestCourse: "Engineering",
    tuition: 52000,
    ranking: 10,
    roi: 85,
    scholarshipRate: 62,
    majorStrength: { engineering: 92, business: 88, law: 86, medicine: 85 },
    details: {
      programStrengths: ["Automotive Engineering", "Ross School of Business", "Sports Management"],
      campusLife: "Legendary school spirit, massive athletic events, and a quintessential college town feel in Ann Arbor.",
      admissionStats: { acceptanceRate: "17.7%", avgSAT: "1350-1530", avgGPA: "3.9" },
    },
  },
  {
    name: "Georgia Tech",
    country: "USA",
    location: "usa_east",
    bestCourse: "Engineering",
    tuition: 33000,
    ranking: 12,
    roi: 89,
    scholarshipRate: 70,
    majorStrength: { "computer science": 92, "ai": 90, engineering: 95, robotics: 93 },
    details: {
      programStrengths: ["Industrial Engineering", "Cybersecurity", "Aerospace"],
      campusLife: "Tech-focused campus in the heart of Atlanta with strong industry partnerships and research focus.",
      admissionStats: { acceptanceRate: "16%", avgSAT: "1370-1530", avgGPA: "4.0" },
    },
  },
  {
    name: "University of British Columbia",
    country: "Canada",
    location: "canada",
    bestCourse: "Environmental Science",
    tuition: 34000,
    ranking: 14,
    roi: 83,
    scholarshipRate: 68,
    majorStrength: { "environmental science": 92, "computer science": 85, engineering: 85 },
    details: {
      programStrengths: ["Sustainability", "Forestry", "International Relations"],
      campusLife: "Stunning coastal campus with a focus on global citizenship and environmental stewardship.",
      admissionStats: { acceptanceRate: "50%", avgGPA: "3.6" },
    },
  },
  {
    name: "Technical University of Munich",
    country: "Germany",
    location: "europe",
    bestCourse: "Engineering",
    tuition: 12000,
    ranking: 15,
    roi: 88,
    scholarshipRate: 80,
    majorStrength: { engineering: 94, "computer science": 89, "ai": 88 },
    details: {
      programStrengths: ["Automotive Systems", "Bioinformatics", "Physics"],
      campusLife: "Leading technical university in Germany with strong ties to major European engineering firms.",
      admissionStats: { acceptanceRate: "8%", avgGPA: "3.7+" },
    },
  },
  {
    name: "University of Tokyo",
    country: "Japan",
    location: "asia",
    bestCourse: "Engineering",
    tuition: 10000,
    ranking: 13,
    roi: 85,
    scholarshipRate: 78,
    majorStrength: { engineering: 92, physics: 91, "ai": 85 },
    details: {
      programStrengths: ["Theoretical Physics", "Electrical Engineering", "Asian Studies"],
      campusLife: "Prestigious institution with a focus on research excellence and traditional Japanese values.",
      admissionStats: { acceptanceRate: "34%", avgGPA: "3.8+" },
    },
  },
  {
    name: "Carnegie Mellon University",
    country: "USA",
    location: "usa_east",
    bestCourse: "Computer Science & AI",
    tuition: 58000,
    ranking: 11,
    roi: 91,
    scholarshipRate: 58,
    majorStrength: { "computer science": 98, "ai": 99, robotics: 98, business: 84 },
    details: {
      programStrengths: ["Robotics", "Software Engineering", "Drama & Arts"],
      campusLife: "Interdisciplinary focus where technology meets the arts, located in a revitalized tech hub.",
      admissionStats: { acceptanceRate: "11%", avgSAT: "1480-1560", avgGPA: "3.91" },
    },
  },
  {
    name: "University of Washington",
    country: "USA",
    location: "usa_west",
    bestCourse: "Computer Science & Medicine",
    tuition: 40000,
    ranking: 16,
    roi: 86,
    scholarshipRate: 66,
    majorStrength: { "computer science": 90, medicine: 90, "ai": 85 },
    details: {
      programStrengths: ["Cloud Computing", "Nursing", "Oceanography"],
      campusLife: "Beautiful campus in Seattle with close proximity to tech giants like Microsoft and Amazon.",
      admissionStats: { acceptanceRate: "47.5%", avgSAT: "1220-1470", avgGPA: "3.8" },
    },
  },
];

export const CAREER_PATHS: CareerPath[] = [
  {
    id: "ai-engineer",
    name: "AI Engineer",
    description: "Design and build intelligent systems that can learn and make decisions.",
    skills: ["Python", "Machine Learning", "Deep Learning", "TensorFlow/PyTorch"],
    roadmap: ["Learn Python", "Study Statistics", "Build ML Models", "Deploy AI Systems"],
    targetCompanies: ["Google", "OpenAI", "Meta", "NVIDIA"]
  },
  {
    id: "doctor",
    name: "Medical Doctor",
    description: "Diagnose and treat patients, conduct research, and improve public health.",
    skills: ["Biology", "Chemistry", "Anatomy", "Clinical Diagnosis"],
    roadmap: ["Pre-med", "Medical School", "Residency", "Specialization"],
    targetCompanies: ["Mayo Clinic", "Johns Hopkins", "NHS", "WHO"]
  },
  {
    id: "btech-engineer",
    name: "B.Tech Engineer",
    description: "Apply engineering principles to solve complex technical problems.",
    skills: ["Mathematics", "Physics", "Problem Solving", "Programming"],
    roadmap: ["B.Tech Degree", "Internships", "Skill Specialization", "Job Search"],
    targetCompanies: ["Tata Consultancy", "Infosys", "IBM", "Intel"]
  },
  {
    id: "data-scientist",
    name: "Data Scientist",
    description: "Analyze complex data to help organizations make better decisions.",
    skills: ["Statistics", "SQL", "Python", "Data Visualization"],
    roadmap: ["Learn Math/Stats", "Master Python/SQL", "Build Portfolio", "Apply for Jobs"],
    targetCompanies: ["Amazon", "Netflix", "Uber", "Airbnb"]
  },
  {
    id: "ux-designer",
    name: "UX Designer",
    description: "Create intuitive and user-friendly digital experiences.",
    skills: ["Figma", "User Research", "Prototyping", "Wireframing"],
    roadmap: ["Learn Design Principles", "Master Figma", "Build Case Studies", "Network"],
    targetCompanies: ["Google", "Apple", "Microsoft", "Adobe"]
  },
  {
    id: "digital-marketer",
    name: "Digital Marketer",
    description: "Promote products and services through online channels.",
    skills: ["SEO", "Content Marketing", "Social Media", "Analytics"],
    roadmap: ["Learn Marketing Basics", "Get Certified (Google/HubSpot)", "Run Campaigns", "Analyze Results"],
    targetCompanies: ["HubSpot", "Shopify", "Nike", "Coca-Cola"]
  }
];
